### PR TITLE
Updated README

### PR DESCRIPTION
**Pull request by KlaussMC**
I changed 'pixel' on line 21 to 'device' because i think it fits better, what do you think?

### CODE REVIEW

**Comment by eladnava** [comment]
Awesome! 🎉

**Comment by eladnava** [comment]
Made 2 tiny tweaks:
https://github.com/eladnava/pixelmate/commit/1909f7a40658b3f1606d157ac989e25ac6736ee2

**Comment by KlaussMC** [comment]
Cool, so you'll do the packaging and distributing?

**Comment by eladnava** [comment]
@KlaussMC Nope, you need a Windows machine to generate a Windows `.exe`.

Try this:
```
rd /s /q dist/
rd /s /q build/

npm run build
electron-packager . Pixelmate --electron-version=1.7.11 --platform=win32 --arch=x64 --icon=public/app.icns --version=1.0.0 --app-bundle-id=com.pixelmate --app-version=1.0.0 --build-version=1.0.0 --overwrite
```

**Comment by KlaussMC** [comment]
I'm not sure why this command needs to be as long as it is, but running it gives back this: `--version does not take an argument. Perhaps you meant --app-version or --electron-version?`

**Comment by eladnava** [comment]
Try `--app-version` instead (it already exists in the params):

```
electron-packager . Pixelmate --electron-version=1.7.11 --platform=win32 --arch=x64 --icon=public/app.icns --app-bundle-id=com.pixelmate --app-version=1.0.0 --build-version=1.0.0 --overwrite
```

**Comment by KlaussMC** [comment]
just don t expect this to be done till christmas

well, see ya at christmas...

**Comment by KlaussMC** [comment]
nvm, 2.3kB/s

**Comment by eladnava** [comment]
I recommend getting on a better Wi-Fi connection then 👍

**Comment by eladnava** [comment]
What the heck you're from Byron Bay? 🤣

**Comment by KlaussMC** [comment]
Yes, Byron, we get 3M+ tourists annually, but my brother and his friend are playing Fortnite. I hate them with passion. they should learn to code, right?

**Comment by eladnava** [comment]
Haha awesome 😆 Well, yes. I started when I was 11 or so. And it was the best decision of my life. Instead of wasting time on games you're being productive and securing yourself a great future, especially if you like this stuff (which seems like you do) 👍

**Comment by KlaussMC** [comment]
yeah, i started 3 - 4 years ago now, and I find it amazing how quickly you can learn if this is something that's really interesting to you.

**Comment by KlaussMC** [comment]
absolutely, you too!

**Comment by eladnava** [comment]
When programming is a passion you pursue since you were young, it is a passion for life. ⚡️

**Comment by KlaussMC** [comment]
that's absolutely right.

**Comment by eladnava** [comment]
Yeah dude! The picture in the Pixelmate post on my blog is from the Cape Byron walk:
image

I stayed in Byron for two weeks. Loved your town mate. 🏄

**Pull request merged**
